### ISSUE TITLE
Categories are not shown on Flathub

### ISSUE THREAD

**Issue by bilelmoussaoui** [flathub/com.mattermost.Desktop#1]
https://flathub.org/apps/details/com.mattermost.Desktop
Must be an issue with the desktop/appdata file

**Comment by SemaiCZE** [comment]
I can add `<categories>` section similar to this https://github.com/flathub/com.slack.Slack/commit/0bc15702545b83eea64d134f92b38a2af8f6c2f0, but I'm not sure if it helps. Many apps on the Flathub have assigned a category, but there is no such value in their repository. Maybe @nedrichards, @TingPing or @x80486 can help?

**Comment by bilelmoussaoui** [comment]
The categories should be put on the desktop file.
