### ISSUE TITLE
authentication on fedora 39 fails

### ISSUE THREAD

**Issue by akallabeth** [flathub/com.mattermost.Desktop#111]
I have a setup with an internal gitlab setup authenticating the mattermost account.

the procedure (which worked until a few days/weeks?) back was:

1. on login screen click `GitLab`
2. browser opens, you authenticate (or just approve the access permission if already logged in)
3. the mattermost flatpak gets the auth token and you´re ready to chat.

now after step 2 nothing happens, mattermost flatpak does not get anything.

(FYI: firefox/rpm is used here)

**Comment by SemaiCZE** [comment]
Hi,

can you try if this executed from your Fedora host helps?
```sh
$ echo "x-scheme-handler/mattermost=com.mattermost.Desktop.desktop;" | sudo tee -a /var/lib/flatpak/exports/share/applications/mimeinfo.cache
```

Thanks.

**Comment by akallabeth** [comment]
that was it, working now.
