### ISSUE TITLE
UI blurry on Fedora 39 GNOME Wayland HiDPI display

### ISSUE THREAD

**Issue by almereyda** [flathub/com.mattermost.Desktop#114]
This Mattermost Desktop Flatpak installation produces a blurry display of the UI on Fedora 39 with Wayland GNOME on a HiDPI display.

This happens with and without the file `~/.local/share/applications/com.mattermost.Desktop.desktop` being present to overlay the stock `.desktop` file:

```sh
$ diff /var/lib/flatpak/exports/share/applications/com.mattermost.Desktop.desktop ~/.local/share/applications/com.mattermost.Desktop.desktop
```

```diff
4c4
< Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=mattermost-flatpak --file-forwarding com.mattermost.Desktop --enable-features=WebRTCPipeWireCapturer @@u %U @@
---
> Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=mattermost-flatpak --file-forwarding --socket=wayland com.mattermost.Desktop --enable-features=WebRTCPipeWireCapturer,UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland @@u %U @@
```

Do other people experience this issue, too?

**Comment by almereyda** [comment]
This also comes with a side-effect that the application starts in a faux maximised window, which leaves a transparent border to the right and to the bottom, but cannot be resized, if another window is present on the same work space. In this case, Meta+Up, Meta+Down, Meta+Up will actually maximise the window. The initial Meta+Up is needed here. Only issuing Meta+Down and Meta+Up will not work to really maximise the window.

**Comment by SemaiCZE** [comment]
I have a Fedora 39 computer, but not a HiDPI display and I don't have any problems. The app starts not maximized and have proper decorations (border, title) and the viewport is not blurry at all. If you have any idea how to fix this please let me know. Do you have similar experience with other flatpak applications?

**Comment by almereyda** [comment]
Please excuse the interruption. Checking the other applications helped.

This was caused by adapted `Exec` commands from `.desktop` file shims copied from `/var/lib/flatpak/exports/share/applications/` into `~/.local/share/applications/`, since moved out of place. Logging out and back in loaded the vendor `.desktop` manifests, and Mattermost type setting was crisp and clear again.

```sh
$ grep Exec .tmp/com.*.desktop
.tmp/com.mattermost.Desktop.desktop
4:Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=mattermost-flatpak --file-forwarding --socket=wayland com.mattermost.Desktop --enable-features=WebRTCPipeWireCapturer,UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland @@u %U @@

.tmp/com.bitwarden.desktop.desktop
3:Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=bitwarden --file-forwarding com.bitwarden.desktop --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland @@u %U @@

.tmp/com.logseq.Logseq.desktop
3:Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=run.sh --file-forwarding --socket=wayland com.logseq.Logseq @@u %U @@ --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-features=WaylandWindowDecorations
```

This appears to be a side-effect from upstream generally moving towards Wayland-by-default, as seen in desktop environments, Electron and application developers plus packagers, with emphasis on the release cycles of the last three in conjunction.

Such patches are not needed anymore, thanks to developments upstream, and 2/3rds of the Flatpaks listed above are Wayland-native now. Sorry for this causing any effort.
