### ISSUE TITLE
Redirecting mattermost links to the app is not working

### ISSUE THREAD

**Issue by jonas-moreonion** [flathub/com.mattermost.Desktop#118]
If I click on an link in my browser it fails to find the desktop client to open it with. This was apparently fixed in the native build here: https://github.com/mattermost/desktop/pull/2917

Is there a possibility to fix this in the flatpak build aswell?

**Comment by SemaiCZE** [comment]
Hi, already fixed and working fine. You must have quite old version.

https://github.com/flathub/com.mattermost.Desktop/commit/5d0f8d2c4c0d91678cdb9b313825626c2098205b
