### ISSUE TITLE
Systray icon does not appear until GNOME AppIndicator extension is reloaded

### ISSUE THREAD

**Issue by toreanderson** [flathub/com.mattermost.Desktop#15]
After starting Mattermost application using `flatpak run com.mattermost.Desktop`, the system tray icon does not appear.

If I, while Mattermost is running, use the GNOME Tweaks application to disable the AppIndicator GNOME Shell extension and then enable it immediately after, the system tray icon shows up.

The official Mattermost AppImage release does not exhibit this behaviour, so the issue is specific to the Flatpak release. That is, after starting the AppImage binary, the system tray icon shows up immediately - I do not need to reload the AppIndicator GNOME Shell extension.

I'm running Fedora 32, GNOME Shell v3.36.5, AppIndicator extension v33, and Mattermost v4.5.3 (both Flatpak and AppImage).

**Comment by SemaiCZE** [comment]
Hi @toreanderson, is it fixed now with #16 ?

**Comment by toreanderson** [comment]
No, I'm afraid not. Same behaviour as before.

**Comment by wmutschl** [comment]
Exactly the same behaviour here on Fedora 33 with GNOME.

**Comment by SemaiCZE** [comment]
Well, I'd like to help you, but I don't know how. I'm just taking the oficial releases and packaging them. I'm using Fedora with Gnome as-is, without any additional AppIndicator, TopIconsPlus, ... extensions and I'm quite happy with that. If you have any ideas what to try, please make a pull request and we can try :slightly_smiling_face:

**Comment by wmutschl** [comment]
Thank you for your efforts and work, it works very well in terms of functionality. No problem. I am trying to figure out how to fix this, as I had a similar issue with the nextcloud icon and was able to fix this using a delay in the startup. I'll let you know if that works for me on Fedora.

**Comment by lunaryorn** [comment]
The app needs to talk `org.kde.StatusNotifierWatcher` for status icons. I've opened #22 to add this permission, meanwhile you can add the permission with e.g. flatseal

**Comment by SemaiCZE** [comment]
@lunaryorn did you test the build and can you confirm it fixes the KDE issues with status bar icon?

**Comment by lunaryorn** [comment]
@SemaiCZE I'm sorry, which issue do you refer to? I thought this issue was about indicators in Gnome?

I didn't test the build in #22, but I added a corresponding override with Flatseal and it works.

**Comment by SemaiCZE** [comment]
@lunaryorn sorry, Gnome icons of course. If it really works, I'll merge your PR and release an update. I just want to hear the the PR is tested by you and it fixes what it suppose to.

**Comment by lunaryorn** [comment]
Sure, I tested the change.
