### ISSUE TITLE
Feature Request: Autostart support

### ISSUE THREAD

**Issue by rmader** [flathub/com.mattermost.Desktop#4]
It would be great to add autostart support, see https://github.com/flatpak/flatpak/issues/118 and https://github.com/flatpak/xdg-desktop-portal/blob/master/data/org.freedesktop.impl.portal.Background.xml

P.S.: Thanks for bringing mattermost to flathub!

**Comment by TingPing** [comment]
Such feature requests should go to the application upstream not the package.

**Comment by rmader** [comment]
Ah ok, will look if there's some issue already for mattermost or electron  concerning this portal
