### ISSUE TITLE
Can't access yubikey

### ISSUE THREAD

**Issue by razzeee** [flathub/com.mattermost.Desktop#56]
The flatpak is not able to access my yubikey, when I need it as a second factor for login.

I've set `socket=pcsc` and `device=all` not sure which one is the correct one, but after restarting the app it worked fine.

**Comment by vchernin** [comment]
Can you please test which one is the correct one? If it's just `socket=pcsc` it seems reasonable enough to add by default. I don't think there is a portal for authentication devices like yubikeys.

**Comment by razzeee** [comment]
I've tested again and `socket=pcsc` is NOT helping. So it was indeed `device=all`, that enabled this to work. I would understand, if you don't want that in the default permissions, but maybe we should have a hint somewhere.

**Comment by vchernin** [comment]
I am admittedly a bit puzzled why in [this issue](https://github.com/flathub/com.axosoft.GitKraken/issues/67) apparently `--socket=pcsc` is the correct permission.

Can you confirm you fully restarted Mattermost?

Since we are already passing home directory permissions maybe `--device=all` isn't too terrible, but then again file chooser portal support has improved in electron.

@SemaiCZE do you have an opinion on adding more permissions?

**Comment by SemaiCZE** [comment]
Well, I don't know. I read some issues about security keys and it seems that `--device=all` is required at the moment to make it work. I'm not totally against this, but I think that I don't know all the consequences.

About file chooser, I need to test that again to see if something improved.

**Comment by razzeee** [comment]
My yubikey is pretty old so maybe it's connected to that somehow. But I can test again.

**Comment by razzeee** [comment]
Checked this again, it's definitely the `device` permission :/

**Comment by SemaiCZE** [comment]
> Checked this again, it's definitely the `device` permission :/

Yes, I looked into [Yubioath flatpak](https://github.com/flathub/com.yubico.yubioath/blob/master/com.yubico.yubioath.yml#L22) and they also give `-device=all` permission. Fun part is that I could use the Yubikey in Mattermost as well, so I'm tempted to add these permissions.

Another option is to change this setting locally using [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal) for those who have some kind of 2FA authentication using security keys.

**Comment by SemaiCZE** [comment]
Flatpak for 5.2.0 has required permissions, enjoy :slightly_smiling_face:
