### ISSUE TITLE
No support for arm64 / aarch64

### ISSUE THREAD

**Issue by kkeijzer** [flathub/com.mattermost.Desktop#61]
Only amd64 builds are available currently, which makes it impossible to install this Flatpak on devices like a Pinebook Pro.

Recently, aarch64 Linux builds have been added to the upstream CI pipelines, and will be included in the next release: https://github.com/mattermost/desktop/pull/2406

It would be useful if this would be added to the next release on Flathub as well.

**Comment by SemaiCZE** [comment]
Note to self: something like https://github.com/flathub/com.sublimemerge.App/commit/55ac1c925ac0a41ddd809c5d70773dd07258f07b

**Comment by SemaiCZE** [comment]
@kkeijzer you can try the ARM 5.2.2-rc1 version from [flathub-beta](https://discourse.flathub.org/t/how-to-use-flathub-beta/2111) or directly from the [builder ref](https://buildbot.flathub.org/#/builders/6/builds/8475).

**Comment by kkeijzer** [comment]
It installs and runs, and crashes in the [exact same way](https://github.com/mattermost/desktop/issues/1476#issuecomment-1322699970) as the .tar.gz release does.

So I guess upstream first has to fix their aarch64 Linux build before I can properly test it, but so far I don't see anything different with the Flatpak compared to the tarball.

**Comment by SemaiCZE** [comment]
> I'm currently testing this tarball on my Pinebook Pro with Debian testing: https://releases.mattermost.com/desktop/5.2.2-rc.3/mattermost-desktop-5.2.2-rc.3-linux-arm64.tar.gz
> 
> It works fine.
> 
> Can a Flatpak be built from this as well?

It's already available in the beta branch. I've set up automatic publishing new releases for the beta branch 🙂
